"""Rendering of the shairport-sync and OwnTone configuration files, and writing them to disk.

Everything in here is deterministic and free of side effects except ``write_config_set``, which
compares what should be on disk with what is, writes only what changed, and reports the difference
so the runner can restart just the affected processes.
"""

from __future__ import annotations

import errno
import os
import stat
from dataclasses import dataclass, field
from pathlib import Path
from string import Template

from .config import Settings
from .groups import Group

SHAIRPORT_TEMPLATE = Template(
    """\
// Generated by AirPlay Mirror for group "$name". Do not edit; regenerated whenever groups change.
general = {
  name = "$name";
  port = $port;
  udp_port_base = $udp_port_base;
  udp_port_range = 10;
  mdns_backend = "avahi";
  output_backend = "pipe";
  airplay_device_id_offset = $offset;
  ignore_volume_control = "no";
  volume_range_db = 60;
  playback_mode = "stereo";
  interpolation = "auto";
};

sessioncontrol = {
  run_this_before_play_begins = "$hook start $id";
  run_this_after_play_ends = "$hook stop $id";
  wait_for_completion = "yes";
  allow_session_interruption = "yes";
  session_timeout = 20;
};

pipe = {
  name = "$pipe";
};

metadata = {
  enabled = "yes";
  include_cover_art = "yes";
  pipe_name = "$pipe.metadata";
  pipe_timeout = 5000;
};

diagnostics = {
  log_verbosity = $verbosity;
};
"""
)

OWNTONE_TEMPLATE = Template(
    """\
# Generated by AirPlay Mirror. Do not edit; regenerated whenever groups change.
general {
\tuid = "root"
\tdb_path = "$owntone_dir/songs3.db"
\tdb_backup_path = "$owntone_dir/songs3.bak"
\tlogfile = "/dev/null"
\tloglevel = "$loglevel"
\twebsocket_port = $ws_port
\ttrusted_networks = { "any" }
\tipv6 = false
\tspeaker_autoselect = false
}

library {
\tname = "AirPlay Mirror"
\tport = $port
\tdirectories = { "$pipes_dir" }
\tpipe_autostart = true
\tfollow_symlinks = false
}

audio {
\tnickname = "Computer"
\ttype = "disabled"
}
$device_blocks"""
)


def libconfig_escape(s: str) -> str:
    """Escape a string for a double-quoted libconfig / libconfuse value."""
    return s.replace("\\", "\\\\").replace('"', '\\"')


def pipe_path(settings: Settings, group: Group) -> str:
    return os.path.join(settings.pipes_dir, group.id)


def shairport_conf_path(settings: Settings, group_id: str) -> str:
    return os.path.join(settings.shairport_dir, f"{group_id}.conf")


def render_shairport_conf(settings: Settings, group: Group) -> str:
    return SHAIRPORT_TEMPLATE.substitute(
        name=libconfig_escape(group.name),
        id=group.id,
        port=settings.port_base + group.slot,
        udp_port_base=settings.udp_port_base + group.slot * 10,
        offset=group.slot,
        pipe=libconfig_escape(pipe_path(settings, group)),
        hook=libconfig_escape(settings.hook_script),
        verbosity=1 if settings.log_level == "debug" else 0,
    )


def _owntone_loglevel(level: str) -> str:
    return {"debug": "debug", "info": "log", "warning": "warning", "error": "warning"}.get(level, "log")


def render_owntone_device_blocks(groups: list[Group]) -> str:
    """One block per real speaker (kept permanently, protocol per flag) and one per group name (excluded).

    OwnTone would otherwise discover our own virtual speakers and offer them as outputs, which is a
    feedback loop waiting to happen.
    """
    speakers: dict[str, bool] = {}
    for g in groups:
        for s in g.speakers:
            key = s.name
            # If any group wants AirPlay 2 for a speaker, keep AirPlay 2 (the per-device setting is global).
            speakers[key] = speakers.get(key, False) or s.airplay2
    blocks = []
    for name in sorted(speakers, key=str.lower):
        blocks.append(
            f'airplay "{libconfig_escape(name)}" {{\n'
            "\tpermanent = true\n"
            "\treconnect = true\n"
            f"\tairplay2_disable = {'false' if speakers[name] else 'true'}\n"
            "}\n"
        )
    for g in sorted(groups, key=lambda g: g.name.lower()):
        blocks.append(f'airplay "{libconfig_escape(g.name)}" {{\n\texclude = true\n}}\n')
    return ("\n" + "\n".join(blocks)) if blocks else ""


def render_owntone_conf(settings: Settings, groups: list[Group]) -> str:
    return OWNTONE_TEMPLATE.substitute(
        owntone_dir=libconfig_escape(settings.owntone_dir),
        loglevel=_owntone_loglevel(settings.log_level),
        ws_port=settings.owntone_ws_port,
        port=settings.owntone_port,
        pipes_dir=libconfig_escape(settings.pipes_dir),
        device_blocks=render_owntone_device_blocks(groups),
    )


@dataclass
class ConfigSet:
    owntone_conf: str
    shairport_confs: dict[str, str]  # group_id -> file contents
    pipes: dict[str, str]  # group_id -> fifo path


@dataclass
class ConfigDiff:
    owntone_changed: bool = False
    changed_groups: set[str] = field(default_factory=set)  # receiver conf written (new or modified)
    removed_groups: set[str] = field(default_factory=set)
    new_pipes: set[str] = field(default_factory=set)


def build_config_set(settings: Settings, groups: list[Group]) -> ConfigSet:
    return ConfigSet(
        owntone_conf=render_owntone_conf(settings, groups),
        shairport_confs={g.id: render_shairport_conf(settings, g) for g in groups},
        pipes={g.id: pipe_path(settings, g) for g in groups},
    )


def _write_if_changed(path: Path, text: str) -> bool:
    try:
        if path.read_text() == text:
            return False
    except OSError:
        pass
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_name(f".{path.name}.tmp")
    tmp.write_text(text)
    os.replace(tmp, path)
    return True


def _ensure_fifo(path: str) -> bool:
    """Create a FIFO at ``path`` if there isn't one. Returns True when it was created."""
    try:
        st = os.stat(path)
    except FileNotFoundError:
        pass
    else:
        if stat.S_ISFIFO(st.st_mode):
            return False
        os.remove(path)
    Path(path).parent.mkdir(parents=True, exist_ok=True)
    try:
        os.mkfifo(path, 0o666)
    except OSError as exc:
        if exc.errno != errno.EEXIST:
            raise
    return True


def write_config_set(settings: Settings, cs: ConfigSet) -> ConfigDiff:
    diff = ConfigDiff()
    diff.owntone_changed = _write_if_changed(Path(settings.owntone_conf), cs.owntone_conf)

    shairport_dir = Path(settings.shairport_dir)
    shairport_dir.mkdir(parents=True, exist_ok=True)
    for group_id, text in cs.shairport_confs.items():
        if _write_if_changed(Path(shairport_conf_path(settings, group_id)), text):
            diff.changed_groups.add(group_id)
    for conf in shairport_dir.glob("*.conf"):
        group_id = conf.stem
        if group_id not in cs.shairport_confs:
            conf.unlink(missing_ok=True)
            diff.removed_groups.add(group_id)

    pipes_dir = Path(settings.pipes_dir)
    pipes_dir.mkdir(parents=True, exist_ok=True)
    for group_id, path in cs.pipes.items():
        if _ensure_fifo(path):
            diff.new_pipes.add(group_id)
        _ensure_fifo(f"{path}.metadata")
    for entry in pipes_dir.iterdir():
        base = entry.name[: -len(".metadata")] if entry.name.endswith(".metadata") else entry.name
        if base not in cs.pipes and not entry.name.startswith("."):
            entry.unlink(missing_ok=True)
            diff.removed_groups.add(base)
    return diff
